[versions]
kotlin = "1.5.30"
androidBuildTools = "7.0.2"
detekt = "1.18.1"
ktlint = "10.2.0"
jacoco = "0.8.7"

androidx-core = "1.6.0"
androidx-appcompat = "1.4.0-beta01"
material = "1.4.0"
androidx-lifecycle = "2.4.0-rc01"
androidx-fragment = "1.3.6"
androidx-navigation = "2.3.5"
compose = "1.0.3"
room = "2.3.0"
work = "2.6.0"

hilt-android = "2.38.1"
hilt-work = "1.0.0"

okhttp = "4.9.1"
retrofit = "2.9.0"
tikxml = "0.8.13" # TODO : [DEPRECATED] Need successor
coil = "1.3.2"

testing-junit = "4.13.2"
testing-core = "1.4.0"
testing-androidx-junit = "1.1.3"
testing-espresso-core = "3.4.0"
testing-barista = "4.2.0"

[libraries]
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "androidBuildTools"}
detektPlugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
ktlintPlugin = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlint" }
jacocoPlugin = { module = "org.jacoco:org.jacoco.core", version.ref = "jacoco" }
hiltAndroidPlugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt-android" }

androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core"}
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat"}
material = { module = "com.google.android.material:material", version.ref = "material"}

androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment"}

androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation"}
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation"}

androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle"}
androidx-lifecycle-viewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle"}
androidx-lifecycle-liveData = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle"}

androidx-composeUi = { module = "androidx.compose.ui:ui", version.ref = "compose"}
androidx-composeUiTooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
androidx-composeMaterial = { module = "androidx.compose.material:material", version.ref = "compose" }
androidx-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }

room-runtime = { module = "androidx.room:room-runtime", version.ref = "room"}
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room"}
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room"}

work-runtime = { module = "androidx.work:work-runtime", version.ref = "work"}
work-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work"}
testing-work = { module = "androidx.work:work-testing", version.ref = "work"}

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt-android"}
hilt-androidCompiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt-android"}
testing-hilt-android = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt-android"}
hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hilt-work"}
hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hilt-work"}

okhttp-core = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp"}
testing-okhttp-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp"}
okhttp-loggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp"}
retrofit-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit"}

tikxml-annotation = { module = "com.tickaroo.tikxml:annotation", version.ref = "tikxml"}
tikxml-core = { module = "com.tickaroo.tikxml:core", version.ref = "tikxml"}
tikxml-retrofitConverter = { module = "com.tickaroo.tikxml:retrofit-converter", version.ref = "tikxml"}
tikxml-processor = { module = "com.tickaroo.tikxml:processor", version.ref = "tikxml"}

coil-core = { module = "io.coil-kt:coil", version.ref = "coil"}
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil"}

testing-junit = { module = "junit:junit", version.ref = "testing-junit"}
testing-androidx-junit = { module = "androidx.test.ext:junit", version.ref = "testing-androidx-junit"}
testing-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "testing-espresso-core"}
testing-core-ktx = { module = "androidx.test:core-ktx", version.ref = "testing-core"}
testing-compose-ui = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose"}
testing-compose-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose"}

testing-barista = { module = "com.adevinta.android:barista", version.ref = "testing-barista"}

[bundles]
androidx-compose = [ "androidx-composeUi", "androidx-composeMaterial", "androidx-composeUiTooling" ]
