name: Build and Test

on:
    push:
        branches: [ main ]
    pull_request:
        types: [ opened, synchronize, reopened, ready_for_review ]

concurrency:
    group: ${{ github.head_ref || github.ref_name }}
    cancel-in-progress: true

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        timeout-minutes: 30

        steps:
            - name: 🛎️ Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: 🏭 Set up our JDK environment
              uses: actions/setup-java@v3
              with:
                  distribution: 'adopt'
                  java-version: '17'

            # Decode Google services configuration file from secrets
            - name: 🔐 Decode google-services.json
              env:
                  FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
              run: echo $FIREBASE_CONFIG > app/google-services.json

            - name: 🔨 Build
              run: ./gradlew assembleDebug testDebugUnitTest koverHtmlReport

    android-tests:
        runs-on: ubuntu-latest
        steps:
            - name: 🛎️ Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Enable KVM
              run: |
                echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
                sudo udevadm control --reload-rules
                sudo udevadm trigger --name-match=kvm

            - name: 🏭 Set up our JDK environment
              uses: actions/setup-java@v3
              with:
                  distribution: 'adopt'
                  java-version: '17'

            # Decode Google services configuration file from secrets
            -   name: 🔐 Decode google-services.json
                env:
                    FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
                run: echo $FIREBASE_CONFIG > app/google-services.json

            - name: Instrumented Tests
              uses: reactivecircus/android-emulator-runner@v2
              with:
                  api-level: 29
                  arch: x86_64
                  profile: "pixel_7"
                  target: "google_apis"
                  force-avd-creation: false
                  disable-animations: true
                  disk-size: 1G
                  heap-size: 1G
                  emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
                  script: ./gradlew connectedDebugAndroidTest

            -   name: Upload test results
                if: always()
                uses: actions/upload-artifact@v4
                with:
                    name: Instrumentation test results (API${{ matrix.configuration.api-level }}) ${{ matrix.configuration.target }}
                    path: |
                        **/build/reports/*
                        **/build/outputs/*/connected/*
