name: Build

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Build, Lint and Test

    # runs-on: ubuntu-latest
    runs-on: macos-latest

    steps:
      ## Checkout and prepare repository ###
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up our JDK environment
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      # Step 2: Decode Google services configuration file
      # - name: Decode google-services.json
      #  env:
      #    FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
      #  run: echo $FIREBASE_CONFIG > app/google-services.json

      # Step 3: Check the code with ktlint, you can remove this job if you don't use ktlint
      # - name: Run Kotlin Linter
      #   run: ./gradlew ktlintDebugCheck

      # Step 3: Check the code with Android linter
      - name: Run Android Linter
        run: ./gradlew lintDebug

      # Step 4: Yun your unit tests
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      # Step 4: Assemble debug apk to send to firebase test lab
      - name: Assemble Debug APK
        run: ./gradlew assembleDebug

      # Step 4: Assemble debug test apk to send to firebase test lab
      - name: Assemble Debug Test APK
        run: ./gradlew assembleDebugAndroidTest

      # Step 5: Run emulator
      - name: Run integration test on emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 27
          target: google_apis
          script: ./gradlew createDebugCoverageReport --stacktrace

      # Step 6: Generate report
      - name: Generate report
        run: ./gradlew jacocoTestReport

      # Step 7: Upload report
      - name: Upload Reports
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: reports
          path: |
            /build/coverage-report
            app/build/reports

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}

  generate-apk:
    name: Generate apk
    runs-on: ubuntu-latest
    needs:
      - build-and-test
    steps:
      ## Checkout and prepare repository ###
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up our JDK environment
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Generate apk
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: build-output
          path: app/build/outputs/apk/debug/app-debug.apk
