name: Publish Alpha

on:
  workflow_dispatch:

jobs:
  generate-release-apk:
    name: Generate Releasable apk/aab
    runs-on: ubuntu-latest
    environment: Release
    timeout-minutes: 30

    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - name: 🏭 Set up our JDK environment
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: 🔐 Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.KEYSTORE }}
        run: |
          TMP_KEYSTORE_FILE_PATH="${RUNNER_TEMP}"/keystore
          mkdir "${TMP_KEYSTORE_FILE_PATH}"
          echo $ENCODED_STRING | base64 -di > "${TMP_KEYSTORE_FILE_PATH}"/keystore_file.jks

      # Decode Google services configuration file from secrets
      - name: 🔐 Decode google-services.json
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: echo $FIREBASE_CONFIG > app/google-services.json

      - name: 🏭 Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: 🔨️ Build Release
        run: ./gradlew app:bundleRelease app:assembleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

      # Upload signed release APK
      - name: 📦 Upload apks
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: |
            **/release/*.apk
            **/release/*.aab

      - name: 📦 Deploy on GitHub
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          title: "Bogadex"
          files: |
            **/release/*-release.apk
            **/release/*-release.aab

      - name: 🚚 Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.GOOGLE_CLOUD_CREDENTIAL_FILE_CONTENT }}
          groups: friends-&-family
          file: app/build/outputs/apk/release/app-release.apk
